import * as z from "zod"

export const exportFormSchema = z.object({
  pile_diameter: z.enum(["60", "100"], { error: "Pile Diameter is required" }),
  job_number: z.string().min(1, { error: "Job Number is required" }),
  job_location: z.string().min(1, { error: "Job Location is required" }),
  pile_number: z.string().min(1, { error: "Pile Number is required" }),
  checked_by: z.string().min(1, { error: "Checked By is required" }),

  soil_profile_id: z.uuid({ error: "Soil Profile is required" }),
  show_description: z.boolean(),
  show_spt: z.boolean(),
  show_moist: z.boolean(),
  show_sat: z.boolean(),
  show_shear_strength: z.boolean(),
  soil_notes: z.string().optional(),

  design_method: z.enum(["method_bs", "method_en", "method_test"], { error: "Please select a design method" }),
  country: z.enum(["uk", "pl", "nl"]).optional(),
  applied_tension_load: z.coerce.number().optional(),
  applied_compression_load: z.coerce.number().optional(),
  permanent_tension_load: z.coerce.number().optional(),
  variable_tension_load: z.coerce.number().optional(),
  permanent_compression_load: z.coerce.number().optional(),
  variable_compression_load: z.coerce.number().optional(),
  horizontal_load: z.coerce.number().optional(),
  structure_rigid: z.boolean().optional(),
  use_characteristic: z.boolean().optional(),
  standardTension: z.coerce.number().optional(),
  standardCompression: z.coerce.number().optional(),
  number_of_tests: z.coerce.number().optional(),
  mean_tensile_rcm: z.coerce.number().optional(),
  min_tensile_rcm: z.coerce.number().optional(),
  mean_compression_rcm: z.coerce.number().optional(),
  min_compression_rcm: z.coerce.number().optional(),
  design_notes: z.string().optional(),
  
  nominal_stress_area: z.coerce.number().positive({ error: "Nominal Stress Area is required" }),
  ultimate_tensile_strength_a480: z.coerce.number().positive({ error: "Ultimate Tensile Strength for A4-80 is required" }),
  steel_bolts_resistance: z.coerce.number().positive({ error: "Steel Bolts Resistance is required" }),
  partial_safety_factor_1: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.1)),
  partial_safety_factor_2: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.25)),
  ultimate_tensile_strength_lm25m: z.coerce.number().positive({ error: "Ultimate Tensile Strength for LM25-M is required" }),
  length_of_engagement: z.coerce.number().positive({ error: "Length of Engagement is required" }),
  pitch_diameter: z.coerce.number().positive({ error: "Pitch Diameter is required" }),
  gross_area: z.coerce.number().positive({ error: "Gross Area of the pile cross-section is required" }),
  proof_strength: z.coerce.number().positive({ error: "0.2% Proof Strength is required" }),
  
  
  global_safety_factor: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.5)),
  uk_safety_factor_tension_yG1: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.35)),
  uk_safety_factor_tension_yQ1: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.5)),
  uk_safety_factor_tension_yT1: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.0)),
  uk_safety_factor_tension_yG2: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.0)),
  uk_safety_factor_tension_yQ2: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.3)),
  uk_safety_factor_tension_yT2: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.5)),
  uk_safety_factor_compression_yG1: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.0)),
  uk_safety_factor_compression_yQ1: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(0)),
  uk_safety_factor_compression_yT1: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.25)),
  uk_safety_factor_compression_yG2: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.0)),
  uk_safety_factor_compression_yQ2: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(0)),
  uk_safety_factor_compression_yT2: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.7)),
  pl_safety_factor_tension_yG: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.0)),
  pl_safety_factor_tension_yQ: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(0)),
  pl_safety_factor_tension_yT: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.15)),
  pl_safety_factor_compression_yG: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.35)),
  pl_safety_factor_compression_yQ: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.5)),
  pl_safety_factor_compression_yT: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.1)),
  nl_safety_factor_tension_yG: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.0)),
  nl_safety_factor_tension_yQ: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(0)),
  nl_safety_factor_tension_yT: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.25)),
  nl_safety_factor_compression_yG: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.0)),
  nl_safety_factor_compression_yQ: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.3)),
  nl_safety_factor_compression_yT: z.preprocess((val) => (val === "" ? undefined : val), z.coerce.number().default(1.15)),
})
export type TexportFormSchema = z.infer<typeof exportFormSchema>
